seed: 1234
gpu_cnt: 1
equation:
  x_dim: 2
model: 
  g_type: mlp
  x_std: 0.01
  derivative: improved-steins
train:
  iteration: 1000
  model_sample_cnt: 1024
  batch:
    domain_size: 100
    domain_sample_cnt: 1024
    boundary_size: 100
    boundary_sample_cnt: 1024
  loss:
    domain: 1.0
    boundary: 300
  lr: 1e-3
  scheduler:
    name: linear # const, linear or step
    step_size: 100
    gamma: 0.5 # required if using step lr
test:
  step: 1000 # evaluate every x epochs
  domain_size: 20000
  batch_size: 500
  model_sample_cnt: 1024